### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by panteparak** [compwright/axios-oauth-client#13]
Any plans for typescript supports? Would love to see it here :)

**Comment by compwright** [comment]
No plans, but will take pull requests if you want to submit one to add it.

**Comment by panteparak** [comment]
I'll get right on it then

**Comment by piwo1984** [comment]
@panteparak any progress so far? I also need the typescript types.

**Comment by xenoterracide** [comment]
you could generate it from jsdoc https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html
