### ISSUE TITLE
oauth.client throws an error after upgrade from 1.5.0 to 2.2.0

### ISSUE THREAD

**Issue by captainalbert** [compwright/axios-oauth-client#37]
![image](https://github.com/user-attachments/assets/ddd884e2-bd59-4cc3-9ec1-4f334edbff94)

![image](https://github.com/user-attachments/assets/b6adae5e-747d-4c22-8235-cd688b8a92c2)

is oauth.client deprecated?

**Comment by compwright** [comment]
Removed, actually.
