### ISSUE TITLE
async method for login

### ISSUE THREAD

**Issue by psobhanlo** [compwright/axios-oauth-client#4]
hi,
when return data from server with status code 401
 

problem in execute try catch

```
        const getOwnerCredentials = oauth.client(axios.create(), {
            url: 'http://backend.com/oauth/token',
            grant_type: 'password',
            client_id: client_id,
            client_secret: client_secret,
            username: user,
            password: password,
        });

 
        const auth =  getOwnerCredentials();
        console.log(auth)
        try {
            if (auth.access_token) {
                localStorage.setItem("token", JSON.stringify(auth.access_token));
             }
            else {
                console.log('e')
             }
        } catch (e) {
            console.log('e')
         }
```

i whant show console.log in catch

**Comment by compwright** [comment]
@psobhanlo `getOwnerCredentials()` is an async function, so you need to add the `await` keyword. It also is advisable to put it inside your try/catch. Try this:

        const getOwnerCredentials = oauth.client(axios.create(), {
            url: 'http://backend.com/oauth/token',
            grant_type: 'password',
            client_id: client_id,
            client_secret: client_secret,
            username: user,
            password: password,
        });

        try {
            const auth =  await getOwnerCredentials();
            console.log(auth)

            if (auth.access_token) {
                localStorage.setItem("token", JSON.stringify(auth.access_token));
            } else {
                console.log('e')
            }
        } catch (e) {
            console.log('e')
        }
