### ISSUE TITLE
401 Invalid client id param value

### ISSUE THREAD

**Issue by RameshAmzur** [compwright/axios-oauth-client#5]
Hi iam getting 401 Invalid client id param value when trying to get the token using Owner Credentials grant flow.

const axios = require('axios');
const oauth = require('axios-oauth-client');
const getOwnerCredentials = oauth.client(axios.create(), {
  url: 'xxxxxxxxx',
  grant_type: 'password',
  client_id: 'xxxxxx',
  client_secret: 'xxxxx',
  username: 'xxxxxx',
  password: 'xxxxx',
  scope: 'xxxxxx'
});

const auth = await getOwnerCredentials();
But with post man and java code iam getting the token. 
Am I doing any thing wrong.

Thank you.

**Comment by compwright** [comment]
@RameshAmzur Looks good to me. I'm guessing something is wrong with your url or one of the credentials.
